# Generated by Django 2.1.7 on 2019-02-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title', models.TextField()),
                ('picture', models.TextField()),
                ('categoryId', models.IntegerField()),
                ('text', models.TextField()),
                ('source', models.TextField()),
            ],
        ),
    ]
