# Generated by Django 2.1.7 on 2019-02-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_auto_20190217_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
