# Generated by Django 2.1.7 on 2019-02-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_news_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='categoryId',
            field=models.IntegerField(default=-1),
        ),
    ]
