# Generated by Django 2.1.7 on 2019-02-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0006_auto_20190218_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['time']},
        ),
    ]
