# Generated by Django 2.1.7 on 2019-02-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0007_auto_20190218_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='lowercaseText',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='lowercaseTitle',
            field=models.TextField(default=''),
        ),
    ]
