# Generated by Django 2.1.7 on 2019-02-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0008_auto_20190218_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='lowercaseTags',
            field=models.TextField(default=''),
        ),
    ]
